import "./globals.css";
import "../../../packages/ui/styles.css";
import { Inter } from "next/font/google";
import { Layout } from "../../../packages/ui/themes/gallery";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Anna Paton Studios",
  description: "Generated by Anna Paton Studios",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-slate-100 text-blue-500 text-lg font-medium">
          header
        </header>
        {children}
        <footer>footer</footer>
      </body>
    </html>
  );
}
